### ISSUE TITLE
3d model

### ISSUE THREAD

**Issue by ddosoff** [Xinyuan-LilyGO/T-Display-S3-AMOLED#17]
Please share 3d model of the board. Step format is preferable.

**Comment by 3Dsf-info** [comment]
For what it's worth, I've made an approximate 3D model of the board for own uses. It's not perfectly accurate, but is adequate for basic work. It's a free download in STL format here:

https://sites.google.com/site/3dsfinfo/lights-for-model-makers-technology-and-techniques/high-rez-microcontroller-displays

**Comment by ddosoff** [comment]
Thanks a lot, btw STL missing colors. Could you share with your nice colors in Step format?
