### ISSUE TITLE
T-Display-S3-AMOLED stop showing anything on the screen

### ISSUE THREAD

**Issue by BMEWCL2** [Xinyuan-LilyGO/T-Display-S3-AMOLED#25]
When I powered up my device this morning, the screen went blank. Is there a way to fix this issue?

I tried different demo programs, but none of them worked. Is it a hardware issue?  If so, would it be possible to confirm it?  

Please let me know your feedback and suggestions.

Best

Will

**Comment by teastainGit** [comment]
What IDE are you using?
It may have done a Library update and overwritten the libraries  from the LilyGO T-Display S3 AMOLED  repository .
Try copying all the repository libraries back into your local library . 
Choose a simple sketch to see if that is the issue.
I have a LilyGO T-Display S3 AMOLED test sketch for TFT_eSPI  that has low requirements!
Let me know, Terry

**Comment by julio-matarranz** [comment]
Dear,
You can check this issue : https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/issues/13#issuecomment-1934407176
Good luck 🙏🏻
