### ISSUE TITLE
Black screen on lilyGo amoled v2.0 

### ISSUE THREAD

**Issue by oOloBolOo** [Xinyuan-LilyGO/T-Display-S3-AMOLED#27]
I can't get the screen to work with this repositoriy examples. The other repo (lilygo-amoled-series) is working fine but I can't find the root of the issue (I'm beginner).
The board works just fine, it connects to wi-fi and prints to serial but the screen is black.
I tested two boards, they work great  but not with this code (Volos examples also have the same result).
Any suggestions?

**Comment by teastainGit** [comment]
This repository is for the type 1 board.
The type 1 and type 2 have very different screens, and so have been split into 2 repos.
If the examples from this repository (see below):
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/tree/master/examples
work fine, then you have a type 2 and are good-to-go!
-Terry

**Comment by oOloBolOo** [comment]
Ok, thank you for fast reply, I will try to adapt  examples.

**Comment by oOloBolOo** [comment]
This repository is for the type 1 board.
Go to:
https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/tree/master/examples
