### ISSUE TITLE
I2C Pin Number ?

### ISSUE THREAD

**Issue by JpEncausse** [Xinyuan-LilyGO/T-Display-S3-AMOLED#31]
Hello,
I was wondering what are I2C Pin number I don't see them on schema ? Is there any ? How to use them ?
Thanks !

**Comment by teastainGit** [comment]
See here, the big graphic halfway down.
https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED
The little 4 pin connector is Grove standard for I/O including I2C.
SDA 43, SCL 44
These pins are are also brought out on the side connector...and you can use any pin for I2C with an ESP32 S3!
