### ISSUE TITLE
Battery voltage ADC is not documented

### ISSUE THREAD

**Issue by crosser** [Xinyuan-LilyGO/T-Display-S3-AMOLED#35]
Schematic picture of the board shows that pin 4 is used as battery ADC input. But I could not find any explanation of how the voltage is divided, and what's Vref value. Consequently, it is not clear now to covert reading from pin 4 into voltage. By looking at the examples provided for _another_ lilygo board, I came up with the formula to reflect readings into the 0 - 100 range for a lipo battery, that seems to do the job. But without documentation or example for this board, I cannot be sure how realistic my numbers are.
```
int batt_percent = (analogRead(PIN_BAT_VOLT)  * 1000 / 6206) - 300;
if (nbat < 0) nbat = 0;
if (nbat > 100) nbat = 100
```
Please consider providing an official explanation and/or example code for converting ADC reading into battery voltage.

**Comment by lewisxhe** [comment]
No need to consider verf, arduino core automatically calculates it, just read the voltage directly and multiply it by 2

https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/blob/edd133335c9f7c38d1e9be2d0eb67371f1f6428e/examples/factory/factory.ino#L143
