### ISSUE TITLE
External SPI Support?

### ISSUE THREAD

**Issue by V8Joel** [Xinyuan-LilyGO/T-Display-S3-AMOLED#5]
Hi Lilygo Team,

I am trying to use my Lilygo T-Display S3 Amoled with an MCP2515 CAN interface for an Automotive project. Does the board support external SPI devices? It's not clear to me which pins, if any, I can connect an SPI peripheral with... Thank you.
![T-Display-S3-AMOLED](https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED/assets/86188831/3ae4939a-e608-4fa2-8967-52e16c312ba6)

**Comment by teastainGit** [comment]
SPI has gotten complicated…it looks like the SPI pins are called FSPI (fast spi), pins 10-14.
-Terry
