### ISSUE TITLE
Board identification, following the instructions, shows wrong info

### ISSUE THREAD

**Issue by dr3x** [Xinyuan-LilyGO/T-Display-S3-AMOLED#6]
Following the steps under the **Arduino** section, my board is identified as **DFRobot Beetle ESP32-C3**
At step 5, in the tools setting, some of the values match, some don't.
For example, flash size shows as 4MB but per the instructions should be 16MB.
CPU frequency should be 240MHz but the max in the dropdown is 160MHz.

**Comment by myspac0** [comment]
Change the board, choose "Esp32S3 Dev module".
This module works very well.

**Comment by dr3x** [comment]
That worked! Thanks
