### ISSUE TITLE
Micropython with LVGL available?

### ISSUE THREAD

**Issue by sam0910** [Xinyuan-LilyGO/T-Display-S3-AMOLED#8]
Greetings!
Thank you for the good product with AMOLED display!

Is it capable of using micropython with LVGL?
I found ESP32 S3 is micropython capable, but I could not find the display driver.

**Comment by nspsck** [comment]
Sadly, esp32s3 is currently not supported by lv_binding_micropython, hence can't be used on a esp32s3 board.
